### ISSUE TITLE
torbrowser-launcher not starting

### ISSUE THREAD

**Issue by trashcan55** [flathub/com.github.micahflee.torbrowser-launcher#5]
torbrowser-launcher won't start, output when running via terminal:

```
flatpak run  com.github.micahflee.torbrowser-launcher

Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.2
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/app/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/app/lib/python3.7/site-packages/torbrowser_launcher/__init__.py", line 70, in main
    common = Common(tor_browser_launcher_version)
  File "/app/lib/python3.7/site-packages/torbrowser_launcher/common.py", line 60, in __init__
    self.build_paths()
  File "/app/lib/python3.7/site-packages/torbrowser_launcher/common.py", line 110, in build_paths
    self.set_gui('error', _("{0} is not writable").format(homedir), [], False)
AttributeError: 'Common' object has no attribute 'set_gui'
```

edit: i'm using manjaro, if this is relevant

**Comment by AsciiWolf** [comment]
Hmm, that's weird. I just tried a clean Tor Browser installation and everything worked fine.

**Comment by trashcan55** [comment]
seems it is no particular flatpak issue anyway: 

https://github.com/micahflee/torbrowser-launcher/issues/418

closing this
